import Foundation

struct Antimicrobial: Identifiable, Hashable, Codable {
    var id: Int
    var drug: String
    var escherichiaColi: Double
    var escherichiaColiESBL: Double
    var escherichiaColiOXA: Double
    var escherichiaColiMBL: Double
    var escherichiaColiKPC: Double
    var klebsiellaSp: Double
    var klebsiellaSpESBL: Double
    var klebsiellaSpOXA: Double
    var klebsiellaSpMBL: Double
    var klebsiellaSpKPC: Double
    var klebsiellaOxytoca: Double
    var klebsiellaOxytocaESBL: Double
    var klebsiellaPneumoniae: Double
    var raoultellaSp: Double
    var serratiaMarcescens: Double
    var yersiniaPseudotuberculosis: Double
    var yersiniaEnterocolitica: Double
    var salmonellaSp: Double
    var escherichiaHermanii: Double
    var hafniaAlvei: Double
    var shigellaSp: Double
    var citrobacterSp: Double
    var citrobacterFreundii: Double
    var citrobacterBraakii: Double
    var enterobacterSp: Double
    var enterobacterSpOXA: Double
    var enterobacterSpMBL: Double
    var enterobacterSpKPC: Double
    var klebsiellaAerogenes: Double
    var providenciaSp: Double
    var morganellaSp: Double
    var proteusMirabilis: Double
    var proteusMirabilisESBL: Double
    var proteusPenneri: Double
    var proteusVulgaris: Double
    var pseudomonasAeruginosa: Double
    var stenotrophomonasMaltophilia: Double
    var acinetobacterSp: Double
    var msConStaphylococci: Double
    var mrConStaphylococci: Double
    var staphylococcusLugdunensis: Double
    var staphylococcusSaprophyticus: Double
    var mssa: Double
    var mrsa: Double
    var enterococcusSp: Double
    var enterococcusFaecalis: Double
    var enterococcusFaecium: Double
    var enterococcusGallinarum: Double
    var enterococcusCasseliflavus: Double
    var streptococciABCG: Double
    var streptococcusPneumoniae: Double
    var streptococcusViridans: Double
    var streptococcusAnginosus: Double
    var haemophilusInfluenzae: Double
    var moraxellaCatarrhalis: Double
    var neisseriaGonorrhoeae: Double
    var neisseriaMeningitidis: Double
    var helicobacterPylori: Double
    var listeriaMonocytogenes: Double
    var pasteurellaMultocida: Double
    var campylobacterJejuni: Double
    var campylobacterColi: Double
    var corynebacteriumSp: Double
    var aerococcusUrinae: Double
    var aerococcusSanguinicola: Double
    var kingellaKingae: Double
    var aeromonasSp: Double
    var aeromonasVeronii: Double
    var aeromonasJandaei: Double
    var aeromonasDhakensis: Double
    var achromobacterXylosoxidans: Double
    var vibrioSp: Double
    var bacillusSp: Double
    var burkholderiaPseudomallei: Double
    var burkholderiaCepacia: Double
    var bacteroidesSp: Double
    var prevotellaSp: Double
    var fusobacteriumNecrophorum: Double
    var clostridiumPerfringens: Double
    var cutibacteriumAcnes: Double
    var clostridioidesDifficile: Double
    var treponemaPallidum: Double
    var borreliaBurgorferi: Double
    var leptospiraInterrogans: Double
    var mycoplasmaHominis: Double
    var mycoplasmaGenitalium: Double
    var ureaplasmaUrealyticum: Double
    var ureaplasmaParvum: Double
    var mycoplasmaPneumoniae: Double
    var legionellaPneumophila: Double
    var francisellaTularensis: Double
    var brucellaSp: Double
    var nocardiaAbscessus: Double
    var nocardiaAsteroides: Double
    var nocardiaBrevicatena: Double
    var nocardiaPaucivorans: Double
    var nocardiaCyriacigeorgica: Double
    var nocardiaFarcinica: Double
    var nocardiaNova: Double
    var nocardiaTransvalensis: Double
    var nocardiaBrasiliensis: Double
    var nocardiaOtitidiscaviarum: Double
    var nocardiaPseudobrasiliensis: Double
    var chlamydiaPsittaci: Double
    var chlamydiaPneumoniae: Double
    var chlamydiaTrachomatis: Double
    var bartonellaSp: Double
    var bordetellaPertussis: Double
    var coxiellaBurnetii: Double
    var capnocytophagaSp: Double
    var eikenellaSp: Double
    var haemophilusDucreyi: Double
    var ehrlichiaChaffeensis: Double
    var anaplasmaPhagocytophilum: Double
    var rickettsiaRickettsi: Double
    
}
