import Foundation

struct Antimicrobial: Identifiable, Hashable, Codable {
    var id: Int
    var drug: String
    var escherichiaColi: Double
    var escherichiaColiEsbl: Double
    var escherichiaColiOxa: Double
    var escherichiaColiMbl: Double
    var escherichiaColiKpc: Double
    var klebsiellaSp: Double
    var klebsiellaSpEsbl: Double
    var klebsiellaSpOxa: Double
    var klebsiellaSpMbl: Double
    var klebsiellaSpKpc: Double
    var serratiaMarcescens: Double
    var yersiniaPseudotuberculosis: Double
    var yersiniaEnterocolitica: Double
    var salmonellaSp: Double
    var escherichiaHermanii: Double
    var hafniaSp: Double
    var shigellaSp: Double
    var citrobacterSp: Double
    var citrobacterSpEsbl: Double
    var citrobacterSpOxa: Double
    var citrobacterSpMbl: Double
    var citrobacterSpKpc: Double
    var citrobacterFreundii: Double
    var citrobacterBraakii: Double
    var enterobacterSp: Double
    var enterobacterSpOxa: Double
    var enterobacterSpMbl: Double
    var enterobacterSpKpc: Double
    var klebsiellaAerogenes: Double
    var providenciaSp: Double
    var morganellaSp: Double
    var proteusMirabilis: Double
    var proteusMirabilisEsbl: Double
    var proteusPenneri: Double
    var proteusVulgaris: Double
    var pseudomonasAeruginosa: Double
    var stenotrophomonasMaltophilia: Double
    var acinetobacterSp: Double
    var msCons: Double
    var staphylococcusCapitis: Double
    var staphylococcusSaprophyticus: Double
    var mrCons: Double
    var mrStaphylococcusCapitis: Double
    var mrStaphylococcusSaprophyticus: Double
    var msSa: Double
    var mrSa: Double
    var enterococcusSp: Double
    var enterococcusSpVRE: Double
    var enterococcusFaecalis: Double
    var enterococcusFaecium: Double
    var enterococcusGallinarum: Double
    var enterococcusCasseliflavus: Double
    var streptococcusGroupabcg: Double
    var streptococcusPneumoniae: Double
    var viridansStreptococci: Double
    var streptococcusAnginosusgroup: Double
    var haemophilusInfluenzae: Double
    var moraxellaCatarrhalis: Double
    var neisseriaGonorrhoeae: Double
    var neisseriaMeningitidis: Double
    var helicobacterPylori: Double
    var bacteroidesSp: Double
    var prevotellaSp: Double
    var fusobacteriumNecrophorum: Double
    var clostridiumPerfringens: Double
    var cutibacteriumAcnes: Double
    var clostridioidesDifficile: Double
    var listeriaMonocytogenes: Double
    var pasteurellaSp: Double
    var campylobacterSp: Double
    var corynebacteriumSp: Double
    var corynebacteriumDiphtheriae: Double
    var corynebacteriumUlcerans: Double
    var aerococcusSp: Double
    var kingellaKingae: Double
    var aeromonasSp: Double
    var aeromonasDhakensis: Double
    var achromobacterXylosoxidans: Double
    var vibrioSp: Double
    var bacillusSp: Double
    var bacillusAnthracis: Double
    var brucellaMelitensis: Double
    var burkholderiaPseudomallei: Double
    var burkholderiacepaciaComplex: Double
    var legionellaPneumophila: Double
    var treponemaPallidum: Double
    var borreliaBurgorferi: Double
    var leptospiraInterrogans: Double
    var mycoplasmaHominis: Double
    var mycoplasmaGenitalium: Double
    var ureaplasmaUrealyticum: Double
    var ureaplasmaParvum: Double
    var mycoplasmaPneumoniae: Double
    var francisellaTularensis: Double
    var nocardiaAbscessus: Double
    var nocardiaAsteroides: Double
    var nocardiaCyriacigeorgica: Double
    var nocardiaFarcinica: Double
    var nocardiaNova: Double
    var nocardiaTransvalensis: Double
    var chlamydiaPsittaci: Double
    var chlamydiaPneumoniae: Double
    var chlamydiaTrachomatis: Double
    var bartonellaHenselae: Double
    var bordetellaPertussis: Double
    var coxiellaBurnetii: Double
    var eikenellaSp: Double
    var haemophilusDucreyi: Double
    var ehrlichiaChaffeensis: Double
    var anaplasmaPhagocytophilum: Double
    var rickettsiaRickettsi: Double
    
}
